#!/bin/bash
ORIG=`mktemp /tmp/mytest.XXXXXX`
NEW=`mktemp /tmp/mytest.XXXXXX`
for i in ael-test*; do
	echo -n Test: $i..................
	(cd $i; ../../../../utils/aelparse -n -d | grep -v -i 'seconds' > ../res.$i)
	sed 's/line:[0-9]*//; /^Executed.*/d' < res.$i > $NEW
	sed 's/line:[0-9]*//; /^Executed.*/d' < ref.$i > $ORIG
	if (diff -q $NEW $ORIG > /dev/null 2>&1 ) then
		echo PASSED
		rm res.$i
	else
		echo %%%%%%FAILED%%%%%%
		diff -u ref.$i res.$i
	fi

done
rm $NEW $ORIG
