#!/bin/sh
clear
VMHOME=/var/spool/asterisk/voicemail
SNDHOME=/var/lib/asterisk/sounds
echo
echo "Enter Voicemail Context of the mailbox you are creating."
echo "The context is the value between the square brackets in"
echo "the voicemail.conf file."
echo "(DEFAULT: default)"
echo -n "Voicemail Context: "
read context
echo
echo "Enter the Mailbox number of the voicemail box you are creating." 
echo -n "Mailbox Number: "
read mailbox

context=${context:-default}

if [ ! -e "${VMHOME}/${context}" ]
	then
	echo
	echo "New Voicemail context.."
	echo "Creating Voicemail context directory..."
	mkdir -p ${VMHOME}/${context}
fi

echo
echo "Creating Voicemail directory..." 
mkdir -p ${VMHOME}/${context}/${mailbox}
echo "Creating INBOX..."
mkdir -p ${VMHOME}/${context}/${mailbox}/INBOX
echo "Creating Default greetings..."
cat ${SNDHOME}/vm-theperson.gsm > ${VMHOME}/${context}/${mailbox}/unavail.gsm
cat ${SNDHOME}/vm-theperson.gsm > ${VMHOME}/${context}/${mailbox}/busy.gsm
cat ${SNDHOME}/vm-extension.gsm > ${VMHOME}/${context}/${mailbox}/greet.gsm
nums=`echo $mailbox | sed 's/./ \0/g'`
for x in $nums; do
	cat ${SNDHOME}/digits/${x}.gsm >> ${VMHOME}/${context}/${mailbox}/unavail.gsm
	cat ${SNDHOME}/digits/${x}.gsm >> ${VMHOME}/${context}/${mailbox}/busy.gsm
	cat ${SNDHOME}/digits/${x}.gsm >> ${VMHOME}/${context}/${mailbox}/greet.gsm
done
cat ${SNDHOME}/vm-isunavail.gsm >> ${VMHOME}/${context}/${mailbox}/unavail.gsm
cat ${SNDHOME}/vm-isonphone.gsm >> ${VMHOME}/${context}/${mailbox}/busy.gsm
echo "Complete."

