#!/bin/bash
SCANBUILD="scan-build"
if [ -z "`which clang`" ]; then
	CCC_CC="clang"
	CCC_CXX="clang++"
	CFLAGS="-fblocks"
else
	CCC_CC="gcc"
	CCC_CXX="g++"
	CFLAGS=""
fi

SCANBUILD_FLAGS="-maxloop 10 -disable-checker deadcode.DeadStores -enable-checker alpha.core.BoolAssignment -enable-checker alpha.core.CallAndMessageUnInitRefArg -enable-checker alpha.core.CastSize -enable-checker alpha.core.CastToStruct -enable-checker alpha.core.IdenticalExpr -enable-checker alpha.core.PointerArithm -enable-checker alpha.core.PointerSub -enable-checker alpha.core.SizeofPtr -enable-checker alpha.core.TestAfterDivZero -enable-checker alpha.security.ArrayBound -enable-checker alpha.security.ArrayBoundV2 -enable-checker alpha.security.MallocOverflow -enable-checker alpha.security.ReturnPtrRange -enable-checker alpha.security.taint.TaintPropagation -enable-checker alpha.unix.MallocWithAnnotations -enable-checker alpha.unix.PthreadLock -enable-checker alpha.unix.SimpleStream -enable-checker alpha.unix.Stream -enable-checker alpha.unix.cstring.BufferOverlap -enable-checker alpha.unix.cstring.NotNullTerminated -enable-checker alpha.unix.cstring.OutOfBounds"

${SCANBUILD} ${SCANBUILD_FLAGS} -o scanbuild-output ./configure --enable-coverage --disable-xmldoc $*
if [ $? == 0 ]; then
	make clean
	${SCANBUILD} ${SCANBUILD_FLAGS} -o scanbuild-output make
fi
