#!/bin/sh

process_dir() {
	dir=${1}
	prefix=${2}_
	catsuffix=${3}
	displayname=${4}

	echo -e "\t<category name=\"MENUSELECT_${catsuffix}\" displayname=\"${displayname}\">"
	for file in ${dir}/${prefix}*.c
	do
		fname=${file##${dir}/}
		echo -e "\t\t<member name=\"${fname%%.c}.so\">"
		awk -f build_tools/get_moduledeps ${file}
		echo -e "\t\t</member>"
	done
	echo -e "\t</category>"
}

echo "<?xml version="1.0"?>"
echo
echo "<menu>"
process_dir apps app APPS Applications
process_dir cdr cdr CDR "Call Detail Recording"
process_dir channels chan CHANNELS "Channel Drivers"
process_dir codecs codec CODECS "Codec Translators"
process_dir formats format FORMATS "Format Interpreters"
process_dir funcs func FUNCS "Diaplan Functions"
process_dir pbx pbx PBX "PBX Modules"
process_dir res res RES "Resource Modules"
cat build_tools/cflags.xml
echo "</menu>"
