#!/bin/sh -e

# This script will be executed by the 'mkrelease' script to do any tasks
# necessary during tarball creation of this project.
#
# It will be executed from the top-level directory of the project.

make -C sounds MENUSELECT_CORE_SOUNDS=CORE-SOUNDS-EN-GSM MENUSELECT_MOH=MOH-OPSOUND-WAV WGET=wget DOWNLOAD=wget all
make AWK=awk GREP=grep menuselect-tree

make_tex_docs() {
    # make backup of asterisk.tex because we are going to alter it
    cp asterisk.tex asterisk.tex.orig
    sed -e "s/ASTERISKVERSION/${VERSION}/" asterisk.tex > asterisk_local.tex
    mv asterisk_local.tex asterisk.tex
    rubber --pdf asterisk.tex
    latex2html asterisk.tex
    # restore backup of asterisk.tex
    mv asterisk.tex.orig asterisk.tex
}

VERSION=`cat .version`
cd doc/tex && make_tex_docs
