#!/bin/sh -e

# This script will be executed by the 'mkrelease' script to do any tasks
# necessary during tarball creation of this project.
#
# It will be executed from the top-level directory of the project.

make -C sounds MENUSELECT_CORE_SOUNDS=CORE-SOUNDS-EN-GSM MENUSELECT_MOH=MOH-OPSOUND-WAV WGET=wget DOWNLOAD=wget all

if ! which wikiexport.py 2>&1 > /dev/null ; then
	echo
	echo "wikiexport.py not found in \${PATH}."
	echo
	echo "Please add repotools into PATH."
	echo "    $ svn co http://svn.asterisk.org/svn/repotools"
	echo
	exit 1
fi

if ! which pdftotext 2>&1 > /dev/null ; then
	echo
	echo "pdftotext not found.  Please install it."
	echo
	echo "On Debian/Ubuntu/Fedora/CentOS, install the poppler-utils package."
	echo
	exit 1
fi

cd doc
echo "Exporting Asterisk wiki to a PDF (this will take a minute) ..."
wikiexport.py
echo "Converting wiki export PDF to plain text ..."
pdftotext AST.pdf
