#!/bin/sh
# vim:textwidth=80:tabstop=4:shiftwidth=4:smartindent:autoindent

CLIARGS="$*"				# Grab any args passed to safe_asterisk
TTY=9						# TTY (if you want one) for Asterisk to run on
CONSOLE=yes					# Whether or not you want a console
#NOTIFY=ben@alkaloid.net	# Who to notify about crashes
#EXEC=/path/to/somescript	# Run this command if Asterisk crashes
MACHINE=`hostname`			# To specify which machine has crashed when getting the mail
DUMPDROP=/tmp
SLEEPSECS=4
ASTSBINDIR=__ASTERISK_SBIN_DIR__
ASTPIDFILE=__ASTERISK_VARRUN_DIR__/asterisk.pid

# comment this line out to have this script _not_ kill all mpg123 processes when
# asterisk exits
KILLALLMPG123=1

# run asterisk with this priority
PRIORITY=0

# set system filemax on supported OSes if this variable is set
# SYSMAXFILES=262144

# set max files open with ulimit. On linux systems, this will be automatically
# set to the system's maximum files open devided by two, if not set here.
# MAXFILES=32768

# Check if Asterisk is already running.  If it is, then bug out, because
# starting safe_asterisk when Asterisk is running is very bad.
VERSION=`${ASTSBINDIR}/asterisk -rx 'core show version'`
if [ "`echo $VERSION | cut -c 1-8`" = "Asterisk" ]; then
	echo "Asterisk is already running.  $0 will exit now."
	exit 1
fi

# since we're going to change priority and open files limits, we need to be
# root. if running asterisk as other users, pass that to asterisk on the command
# line.
# if we're not root, fall back to standard everything.
if [ `id -u` != 0 ]
then
	echo "Oops. I'm not root. Falling back to standard prio and file max." >&2
	echo "This is NOT suitable for large systems." >&2
	PRIORITY=0
else
	if `uname -s | grep Linux 2>&1 > /dev/null `
	then
		# maximum number of open files is set to the system maximum divided by two if
		# MAXFILES is not set.
		if [ "$MAXFILES" = "" ]
		then
			# just check if file-max is readable
			if [ -r /proc/sys/fs/file-max ]
			then
				MAXFILES=$(( `cat /proc/sys/fs/file-max` / 2 ))
			fi
		fi
		SYSCTL_MAXFILES="fs.file-max"
	elif `uname -s | grep Darwin 2>&1 > /dev/null `
	then
		SYSCTL_MAXFILES="kern.maxfiles"
	fi


	if [ "$SYSMAXFILES" != "" ]
	then
		if [ "$SYSCTL_MAXFILES" != "" ]
		then
			sysctl -w $SYSCTL_MAXFILES=$SYSMAXFILES
		fi
	fi

	# set the process's filemax to whatever set above
	ulimit -n $MAXFILES

fi

#
# Let Asterisk dump core
#
ulimit -c unlimited

#
# Don't fork when running "safely"
#
ASTARGS=""
if [ "$TTY" != "" ]; then
	if [ -c /dev/tty${TTY} ]; then
		TTY=tty${TTY}
	elif [ -c /dev/vc/${TTY} ]; then
		TTY=vc/${TTY}
	else
		echo "Cannot find your TTY (${TTY})" >&2
		exit 1
	fi
	ASTARGS="${ASTARGS} -vvvg"
	if [ "$CONSOLE" != "no" ]; then
		ASTARGS="${ASTARGS} -c"
	fi
fi
if [ ! -w ${DUMPDROP} ]; then	
	echo "Cannot write to ${DUMPDROP}" >&2
	exit 1
fi

#
# Don't die if stdout/stderr can't be written to
#
trap '' PIPE

#
# Run scripts to set any environment variables or do any other system-specific setup needed
#

if [ -d /etc/asterisk/startup.d ]; then
	for script in /etc/asterisk/startup.d/*.sh; do
		if [ -x ${script} ]; then
			. ${script}
		fi
	done
fi

run_asterisk()
{
	while :; do 

		if [ "$TTY" != "" ]; then
			cd /tmp
			stty sane < /dev/${TTY}
			nice -n $PRIORITY ${ASTSBINDIR}/asterisk -f ${CLIARGS} ${ASTARGS} >& /dev/${TTY} < /dev/${TTY}
		else
			cd /tmp
			nice -n $PRIORITY ${ASTSBINDIR}/asterisk -f ${CLIARGS} ${ASTARGS}
		fi
		EXITSTATUS=$?
		echo "Asterisk ended with exit status $EXITSTATUS"
		if [ "$EXITSTATUS" = "0" ]; then
			# Properly shutdown....
			echo "Asterisk shutdown normally."
			exit 0
		elif [ $EXITSTATUS -gt 128 ]; then
			EXITSIGNAL=EXITSTATUS-128
			echo "Asterisk exited on signal $EXITSIGNAL."
			if [ "$NOTIFY" != "" ]; then
				echo "Asterisk on $MACHINE exited on signal $EXITSIGNAL.  Might want to take a peek." | \
				mail -s "Asterisk Died" $NOTIFY
			fi
			if [ "$EXEC" != "" ]; then
				$EXEC
			fi

			PID=`cat ${ASTPIDFILE}`
			if [ -f /tmp/core.${PID} ]; then
				mv /tmp/core.${PID} ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
			elif [ -f /tmp/core ]; then
				mv /tmp/core ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
			fi
		else
			echo "Asterisk died with code $EXITSTATUS."

			PID=`cat ${ASTPIDFILE}`
			if [ -f /tmp/core.${PID} ]; then
				mv /tmp/core.${PID} ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
			elif [ -f /tmp/core ]; then
				mv /tmp/core ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
			fi
		fi
		echo "Automatically restarting Asterisk."
		sleep $SLEEPSECS
		if [ $KILLALLMPG123 ]
		then
			killall -9 mpg123
		fi
	done
}

run_asterisk &
