name: Bug
description: File a bug report
title: "[bug]: "
labels: ["bug", "triage"]
#assignees:
#  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a report! The issue has entered the triage process. That means the issue will wait in this status until a Bug Marshal has an opportunity to review the issue. Once the issue has been reviewed you will receive comments regarding the next steps towards resolution. Please note that log messages and other files should not be sent to the Sangoma Asterisk Team unless explicitly asked for. All files should be placed on this issue in a sanitized fashion as needed.

        A good first step is for you to review the Asterisk Issue Guidelines if you haven't already. The guidelines detail what is expected from an Asterisk issue report.

        Then, if you are submitting a patch, please review the Patch Contribution Process.

        Please note that once your issue enters an open state it has been accepted. As Asterisk is an open source project there is no guarantee or timeframe on when your issue will be looked into. If you need expedient resolution you will need to find and pay a suitable developer. Asking for an update on your issue will not yield any progress on it and will not result in a response. All updates are posted to the issue when they occur.

        Please note that by submitting data, code, or documentation to Sangoma through GitHub, you accept the Terms of Use present at
        https://www.asterisk.org/terms-of-use/.      
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Trivial
        - Minor
        - Major
        - Critical
        - Blocker
    validations:
      required: true
  - type: input
    id: versions
    attributes:
      label: Versions
      description: Enter one or more versions separated by commas.
    validations:
      required: true
  - type: input
    id: components
    attributes:
      label: Components/Modules
      description: Enter one or more components or modules separated by commas.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Operating Environment
      description: OS,  Disribution, Version, etc.
    validations:
      required: true
  - type: dropdown
    id: frequency
    attributes:
      label: Frequency of Occurrence
      options:
        - "Never"
        - "One Time"
        - "Occasional"
        - "Frequent"
        - "Constant"
  - type: textarea
    id: description
    attributes:
      label: Issue Description
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        [Asterisk Issue Guidelines](https://docs.asterisk.org/Asterisk-Community/Asterisk-Issue-Guidelines/)
  - type: checkboxes
    id: guidelines
    attributes:
      label: Asterisk Issue Guidelines
      options:
        - label: Yes, I have read the Asterisk Issue Guidelines
          required: true
