blank_issues_enabled: false
contact_links:
  - name: Asterisk Community Support
    url: https://community.asterisk.org
    about: Please ask and answer questions here.
  - name: Feature Requests
    url: https://github.com/asterisk/asterisk-feature-requests/issues
    about: Please submit feature requests here.
