#!/bin/sh

PARTS=`LANG=C svn info | grep URL | awk '{print $2;}' | sed -e 's:^.*/svn/asterisk/::' | sed -e 's:/: :g'`
BRANCH=0
TEAM=0
TAG=0

REV=`svnversion -c . | cut -d: -f2`

if [ "${PARTS}" = "trunk" ]
then
    echo 'trunk'-r${REV}
    exit 0
fi

for PART in $PARTS
do
  if [ ${TAG} != 0 ]
  then
      RESULT="${PART}"
      break
  fi

  if [ ${BRANCH} != 0 ]
  then
      RESULT="${RESULT}-${PART}"
      break
  fi

  if [ ${TEAM} != 0 ]
  then
      RESULT="${RESULT}-${PART}"
      continue
  fi

  if [ "${PART}" = "branches" ]
  then
      BRANCH=1
      RESULT="branch"
      continue
  fi

  if [ "${PART}" = "tags" ]
  then
      TAG=1
      continue
  fi

  if [ "${PART}" = "team" ]
  then
      TEAM=1
      continue
  fi
done

if [ ${TAG} != 0 ]
then
    echo ${RESULT}
else
    echo ${RESULT##-}-r${REV}
fi
