#
# Asterisk -- An open source telephony toolkit.
#
# Makefile for CEL backends
#
# Copyright (C) 1999-2008, Digium, Inc.
#
# This program is free software, distributed under the terms of
# the GNU General Public License
#

-include $(ASTTOPDIR)/menuselect.makeopts $(ASTTOPDIR)/menuselect.makedeps

MODULE_PREFIX=cel
MENUSELECT_CATEGORY=CEL
MENUSELECT_DESCRIPTION=Channel Event Logging

all: _all

include $(ASTTOPDIR)/Makefile.moddir_rules
