/*
 * Asterisk -- An open source telephony toolkit.
 *
 * Copyright (C) 2013, Digium, Inc.
 *
 * See http://www.asterisk.org for more information about
 * the Asterisk project. Please do not directly contact
 * any of the maintainers of this project for assistance;
 * the project provides a web site, mailing lists and IRC
 * channels for your use.
 *
 * This program is free software, distributed under the terms of
 * the GNU General Public License Version 2. See the LICENSE file
 * at the top of the source tree.
 */

/*! \file
 *
 * \brief Generated file - Build validators for ARI model objects.
 */

 /*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!!!!                               DO NOT EDIT                        !!!!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * This file is generated by a mustache template. Please see the original
 * template in rest-api-templates/ari_model_validators.h.mustache
 */

#include "asterisk.h"

ASTERISK_FILE_VERSION(__FILE__, "$Revision$")

#include "asterisk/logger.h"
#include "asterisk/module.h"
#include "ari_model_validators.h"

int ari_validate_asterisk_info(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		{
			ast_log(LOG_ERROR,
				"ARI AsteriskInfo has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	return res;
}

ari_validator ari_validate_asterisk_info_fn(void)
{
	return ari_validate_asterisk_info;
}

int ari_validate_endpoint(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_channel_ids = 0;
	int has_resource = 0;
	int has_technology = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("channel_ids", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel_ids = 1;
			prop_is_valid = ari_validate_list(
				ast_json_object_iter_value(iter),
				ari_validate_string);
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Endpoint field channel_ids failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("resource", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_resource = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Endpoint field resource failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("state", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Endpoint field state failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("technology", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_technology = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Endpoint field technology failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI Endpoint has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_channel_ids) {
		ast_log(LOG_ERROR, "ARI Endpoint missing required field channel_ids\n");
		res = 0;
	}

	if (!has_resource) {
		ast_log(LOG_ERROR, "ARI Endpoint missing required field resource\n");
		res = 0;
	}

	if (!has_technology) {
		ast_log(LOG_ERROR, "ARI Endpoint missing required field technology\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_endpoint_fn(void)
{
	return ari_validate_endpoint;
}

int ari_validate_caller_id(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_name = 0;
	int has_number = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("name", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_name = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI CallerID field name failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("number", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_number = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI CallerID field number failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI CallerID has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_name) {
		ast_log(LOG_ERROR, "ARI CallerID missing required field name\n");
		res = 0;
	}

	if (!has_number) {
		ast_log(LOG_ERROR, "ARI CallerID missing required field number\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_caller_id_fn(void)
{
	return ari_validate_caller_id;
}

int ari_validate_channel(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_accountcode = 0;
	int has_caller = 0;
	int has_connected = 0;
	int has_creationtime = 0;
	int has_dialplan = 0;
	int has_id = 0;
	int has_name = 0;
	int has_state = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("accountcode", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_accountcode = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Channel field accountcode failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("caller", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_caller = 1;
			prop_is_valid = ari_validate_caller_id(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Channel field caller failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("connected", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_connected = 1;
			prop_is_valid = ari_validate_caller_id(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Channel field connected failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("creationtime", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_creationtime = 1;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Channel field creationtime failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("dialplan", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_dialplan = 1;
			prop_is_valid = ari_validate_dialplan_cep(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Channel field dialplan failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("id", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_id = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Channel field id failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("name", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_name = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Channel field name failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("state", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_state = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Channel field state failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI Channel has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_accountcode) {
		ast_log(LOG_ERROR, "ARI Channel missing required field accountcode\n");
		res = 0;
	}

	if (!has_caller) {
		ast_log(LOG_ERROR, "ARI Channel missing required field caller\n");
		res = 0;
	}

	if (!has_connected) {
		ast_log(LOG_ERROR, "ARI Channel missing required field connected\n");
		res = 0;
	}

	if (!has_creationtime) {
		ast_log(LOG_ERROR, "ARI Channel missing required field creationtime\n");
		res = 0;
	}

	if (!has_dialplan) {
		ast_log(LOG_ERROR, "ARI Channel missing required field dialplan\n");
		res = 0;
	}

	if (!has_id) {
		ast_log(LOG_ERROR, "ARI Channel missing required field id\n");
		res = 0;
	}

	if (!has_name) {
		ast_log(LOG_ERROR, "ARI Channel missing required field name\n");
		res = 0;
	}

	if (!has_state) {
		ast_log(LOG_ERROR, "ARI Channel missing required field state\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_fn(void)
{
	return ari_validate_channel;
}

int ari_validate_dialed(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		{
			ast_log(LOG_ERROR,
				"ARI Dialed has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	return res;
}

ari_validator ari_validate_dialed_fn(void)
{
	return ari_validate_dialed;
}

int ari_validate_dialplan_cep(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_context = 0;
	int has_exten = 0;
	int has_priority = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("context", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_context = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI DialplanCEP field context failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("exten", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_exten = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI DialplanCEP field exten failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("priority", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_priority = 1;
			prop_is_valid = ari_validate_long(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI DialplanCEP field priority failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI DialplanCEP has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_context) {
		ast_log(LOG_ERROR, "ARI DialplanCEP missing required field context\n");
		res = 0;
	}

	if (!has_exten) {
		ast_log(LOG_ERROR, "ARI DialplanCEP missing required field exten\n");
		res = 0;
	}

	if (!has_priority) {
		ast_log(LOG_ERROR, "ARI DialplanCEP missing required field priority\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_dialplan_cep_fn(void)
{
	return ari_validate_dialplan_cep;
}

int ari_validate_bridge(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_bridge_class = 0;
	int has_bridge_type = 0;
	int has_channels = 0;
	int has_id = 0;
	int has_technology = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("bridge_class", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_bridge_class = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Bridge field bridge_class failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("bridge_type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_bridge_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Bridge field bridge_type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channels", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channels = 1;
			prop_is_valid = ari_validate_list(
				ast_json_object_iter_value(iter),
				ari_validate_string);
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Bridge field channels failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("id", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_id = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Bridge field id failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("technology", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_technology = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Bridge field technology failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI Bridge has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_bridge_class) {
		ast_log(LOG_ERROR, "ARI Bridge missing required field bridge_class\n");
		res = 0;
	}

	if (!has_bridge_type) {
		ast_log(LOG_ERROR, "ARI Bridge missing required field bridge_type\n");
		res = 0;
	}

	if (!has_channels) {
		ast_log(LOG_ERROR, "ARI Bridge missing required field channels\n");
		res = 0;
	}

	if (!has_id) {
		ast_log(LOG_ERROR, "ARI Bridge missing required field id\n");
		res = 0;
	}

	if (!has_technology) {
		ast_log(LOG_ERROR, "ARI Bridge missing required field technology\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_bridge_fn(void)
{
	return ari_validate_bridge;
}

int ari_validate_live_recording(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_id = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("id", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_id = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI LiveRecording field id failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI LiveRecording has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_id) {
		ast_log(LOG_ERROR, "ARI LiveRecording missing required field id\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_live_recording_fn(void)
{
	return ari_validate_live_recording;
}

int ari_validate_stored_recording(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_formats = 0;
	int has_id = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("duration_seconds", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_int(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StoredRecording field duration_seconds failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("formats", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_formats = 1;
			prop_is_valid = ari_validate_list(
				ast_json_object_iter_value(iter),
				ari_validate_string);
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StoredRecording field formats failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("id", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_id = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StoredRecording field id failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("time", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StoredRecording field time failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI StoredRecording has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_formats) {
		ast_log(LOG_ERROR, "ARI StoredRecording missing required field formats\n");
		res = 0;
	}

	if (!has_id) {
		ast_log(LOG_ERROR, "ARI StoredRecording missing required field id\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_stored_recording_fn(void)
{
	return ari_validate_stored_recording;
}

int ari_validate_format_lang_pair(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_format = 0;
	int has_language = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("format", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_format = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI FormatLangPair field format failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("language", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_language = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI FormatLangPair field language failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI FormatLangPair has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_format) {
		ast_log(LOG_ERROR, "ARI FormatLangPair missing required field format\n");
		res = 0;
	}

	if (!has_language) {
		ast_log(LOG_ERROR, "ARI FormatLangPair missing required field language\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_format_lang_pair_fn(void)
{
	return ari_validate_format_lang_pair;
}

int ari_validate_sound(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_formats = 0;
	int has_id = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("formats", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_formats = 1;
			prop_is_valid = ari_validate_list(
				ast_json_object_iter_value(iter),
				ari_validate_format_lang_pair);
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Sound field formats failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("id", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_id = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Sound field id failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("text", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Sound field text failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI Sound has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_formats) {
		ast_log(LOG_ERROR, "ARI Sound missing required field formats\n");
		res = 0;
	}

	if (!has_id) {
		ast_log(LOG_ERROR, "ARI Sound missing required field id\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_sound_fn(void)
{
	return ari_validate_sound;
}

int ari_validate_playback(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_id = 0;
	int has_media_uri = 0;
	int has_state = 0;
	int has_target_uri = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("id", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_id = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Playback field id failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("language", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Playback field language failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("media_uri", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_media_uri = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Playback field media_uri failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("state", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_state = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Playback field state failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("target_uri", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_target_uri = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Playback field target_uri failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI Playback has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_id) {
		ast_log(LOG_ERROR, "ARI Playback missing required field id\n");
		res = 0;
	}

	if (!has_media_uri) {
		ast_log(LOG_ERROR, "ARI Playback missing required field media_uri\n");
		res = 0;
	}

	if (!has_state) {
		ast_log(LOG_ERROR, "ARI Playback missing required field state\n");
		res = 0;
	}

	if (!has_target_uri) {
		ast_log(LOG_ERROR, "ARI Playback missing required field target_uri\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_playback_fn(void)
{
	return ari_validate_playback;
}

int ari_validate_application_replaced(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ApplicationReplaced field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ApplicationReplaced field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ApplicationReplaced field type failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ApplicationReplaced has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ApplicationReplaced missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ApplicationReplaced missing required field type\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_application_replaced_fn(void)
{
	return ari_validate_application_replaced;
}

int ari_validate_bridge_created(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_bridge = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeCreated field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeCreated field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeCreated field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("bridge", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_bridge = 1;
			prop_is_valid = ari_validate_bridge(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeCreated field bridge failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI BridgeCreated has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI BridgeCreated missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI BridgeCreated missing required field type\n");
		res = 0;
	}

	if (!has_bridge) {
		ast_log(LOG_ERROR, "ARI BridgeCreated missing required field bridge\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_bridge_created_fn(void)
{
	return ari_validate_bridge_created;
}

int ari_validate_bridge_destroyed(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_bridge = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeDestroyed field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeDestroyed field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeDestroyed field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("bridge", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_bridge = 1;
			prop_is_valid = ari_validate_bridge(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeDestroyed field bridge failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI BridgeDestroyed has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI BridgeDestroyed missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI BridgeDestroyed missing required field type\n");
		res = 0;
	}

	if (!has_bridge) {
		ast_log(LOG_ERROR, "ARI BridgeDestroyed missing required field bridge\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_bridge_destroyed_fn(void)
{
	return ari_validate_bridge_destroyed;
}

int ari_validate_bridge_merged(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_bridge = 0;
	int has_bridge_from = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeMerged field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeMerged field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeMerged field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("bridge", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_bridge = 1;
			prop_is_valid = ari_validate_bridge(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeMerged field bridge failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("bridge_from", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_bridge_from = 1;
			prop_is_valid = ari_validate_bridge(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI BridgeMerged field bridge_from failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI BridgeMerged has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI BridgeMerged missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI BridgeMerged missing required field type\n");
		res = 0;
	}

	if (!has_bridge) {
		ast_log(LOG_ERROR, "ARI BridgeMerged missing required field bridge\n");
		res = 0;
	}

	if (!has_bridge_from) {
		ast_log(LOG_ERROR, "ARI BridgeMerged missing required field bridge_from\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_bridge_merged_fn(void)
{
	return ari_validate_bridge_merged;
}

int ari_validate_channel_caller_id(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_caller_presentation = 0;
	int has_caller_presentation_txt = 0;
	int has_channel = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelCallerId field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelCallerId field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelCallerId field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("caller_presentation", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_caller_presentation = 1;
			prop_is_valid = ari_validate_int(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelCallerId field caller_presentation failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("caller_presentation_txt", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_caller_presentation_txt = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelCallerId field caller_presentation_txt failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelCallerId field channel failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelCallerId has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelCallerId missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelCallerId missing required field type\n");
		res = 0;
	}

	if (!has_caller_presentation) {
		ast_log(LOG_ERROR, "ARI ChannelCallerId missing required field caller_presentation\n");
		res = 0;
	}

	if (!has_caller_presentation_txt) {
		ast_log(LOG_ERROR, "ARI ChannelCallerId missing required field caller_presentation_txt\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI ChannelCallerId missing required field channel\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_caller_id_fn(void)
{
	return ari_validate_channel_caller_id;
}

int ari_validate_channel_created(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_channel = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelCreated field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelCreated field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelCreated field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelCreated field channel failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelCreated has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelCreated missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelCreated missing required field type\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI ChannelCreated missing required field channel\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_created_fn(void)
{
	return ari_validate_channel_created;
}

int ari_validate_channel_destroyed(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_cause = 0;
	int has_cause_txt = 0;
	int has_channel = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDestroyed field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDestroyed field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDestroyed field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("cause", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_cause = 1;
			prop_is_valid = ari_validate_int(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDestroyed field cause failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("cause_txt", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_cause_txt = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDestroyed field cause_txt failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDestroyed field channel failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelDestroyed has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelDestroyed missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelDestroyed missing required field type\n");
		res = 0;
	}

	if (!has_cause) {
		ast_log(LOG_ERROR, "ARI ChannelDestroyed missing required field cause\n");
		res = 0;
	}

	if (!has_cause_txt) {
		ast_log(LOG_ERROR, "ARI ChannelDestroyed missing required field cause_txt\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI ChannelDestroyed missing required field channel\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_destroyed_fn(void)
{
	return ari_validate_channel_destroyed;
}

int ari_validate_channel_dialplan(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_channel = 0;
	int has_dialplan_app = 0;
	int has_dialplan_app_data = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDialplan field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDialplan field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDialplan field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDialplan field channel failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("dialplan_app", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_dialplan_app = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDialplan field dialplan_app failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("dialplan_app_data", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_dialplan_app_data = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDialplan field dialplan_app_data failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelDialplan has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelDialplan missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelDialplan missing required field type\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI ChannelDialplan missing required field channel\n");
		res = 0;
	}

	if (!has_dialplan_app) {
		ast_log(LOG_ERROR, "ARI ChannelDialplan missing required field dialplan_app\n");
		res = 0;
	}

	if (!has_dialplan_app_data) {
		ast_log(LOG_ERROR, "ARI ChannelDialplan missing required field dialplan_app_data\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_dialplan_fn(void)
{
	return ari_validate_channel_dialplan;
}

int ari_validate_channel_dtmf_received(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_channel = 0;
	int has_digit = 0;
	int has_duration_ms = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDtmfReceived field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDtmfReceived field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDtmfReceived field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDtmfReceived field channel failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("digit", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_digit = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDtmfReceived field digit failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("duration_ms", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_duration_ms = 1;
			prop_is_valid = ari_validate_int(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelDtmfReceived field duration_ms failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelDtmfReceived has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelDtmfReceived missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelDtmfReceived missing required field type\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI ChannelDtmfReceived missing required field channel\n");
		res = 0;
	}

	if (!has_digit) {
		ast_log(LOG_ERROR, "ARI ChannelDtmfReceived missing required field digit\n");
		res = 0;
	}

	if (!has_duration_ms) {
		ast_log(LOG_ERROR, "ARI ChannelDtmfReceived missing required field duration_ms\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_dtmf_received_fn(void)
{
	return ari_validate_channel_dtmf_received;
}

int ari_validate_channel_entered_bridge(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_bridge = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelEnteredBridge field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelEnteredBridge field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelEnteredBridge field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("bridge", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_bridge = 1;
			prop_is_valid = ari_validate_bridge(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelEnteredBridge field bridge failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelEnteredBridge field channel failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelEnteredBridge has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelEnteredBridge missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelEnteredBridge missing required field type\n");
		res = 0;
	}

	if (!has_bridge) {
		ast_log(LOG_ERROR, "ARI ChannelEnteredBridge missing required field bridge\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_entered_bridge_fn(void)
{
	return ari_validate_channel_entered_bridge;
}

int ari_validate_channel_hangup_request(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_channel = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelHangupRequest field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelHangupRequest field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelHangupRequest field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("cause", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_int(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelHangupRequest field cause failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelHangupRequest field channel failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("soft", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_boolean(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelHangupRequest field soft failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelHangupRequest has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelHangupRequest missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelHangupRequest missing required field type\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI ChannelHangupRequest missing required field channel\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_hangup_request_fn(void)
{
	return ari_validate_channel_hangup_request;
}

int ari_validate_channel_left_bridge(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_bridge = 0;
	int has_channel = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelLeftBridge field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelLeftBridge field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelLeftBridge field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("bridge", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_bridge = 1;
			prop_is_valid = ari_validate_bridge(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelLeftBridge field bridge failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelLeftBridge field channel failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelLeftBridge has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelLeftBridge missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelLeftBridge missing required field type\n");
		res = 0;
	}

	if (!has_bridge) {
		ast_log(LOG_ERROR, "ARI ChannelLeftBridge missing required field bridge\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI ChannelLeftBridge missing required field channel\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_left_bridge_fn(void)
{
	return ari_validate_channel_left_bridge;
}

int ari_validate_channel_state_change(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_channel = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelStateChange field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelStateChange field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelStateChange field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelStateChange field channel failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelStateChange has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelStateChange missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelStateChange missing required field type\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI ChannelStateChange missing required field channel\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_state_change_fn(void)
{
	return ari_validate_channel_state_change;
}

int ari_validate_channel_userevent(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_channel = 0;
	int has_eventname = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelUserevent field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelUserevent field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelUserevent field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelUserevent field channel failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("eventname", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_eventname = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelUserevent field eventname failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelUserevent has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelUserevent missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelUserevent missing required field type\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI ChannelUserevent missing required field channel\n");
		res = 0;
	}

	if (!has_eventname) {
		ast_log(LOG_ERROR, "ARI ChannelUserevent missing required field eventname\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_userevent_fn(void)
{
	return ari_validate_channel_userevent;
}

int ari_validate_channel_varset(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_value = 0;
	int has_variable = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelVarset field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelVarset field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelVarset field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelVarset field channel failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("value", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_value = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelVarset field value failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("variable", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_variable = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI ChannelVarset field variable failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI ChannelVarset has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI ChannelVarset missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI ChannelVarset missing required field type\n");
		res = 0;
	}

	if (!has_value) {
		ast_log(LOG_ERROR, "ARI ChannelVarset missing required field value\n");
		res = 0;
	}

	if (!has_variable) {
		ast_log(LOG_ERROR, "ARI ChannelVarset missing required field variable\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_channel_varset_fn(void)
{
	return ari_validate_channel_varset;
}

int ari_validate_event(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	const char *discriminator;

	discriminator = ast_json_string_get(ast_json_object_get(json, "type"));
	if (!discriminator) {
		ast_log(LOG_ERROR, "ARI Event missing required field type");
		return 0;
	}

	if (strcmp("Event", discriminator) == 0) {
		/* Self type; fall through */
	} else
	if (strcmp("ApplicationReplaced", discriminator) == 0) {
		return ari_validate_application_replaced(json);
	} else
	if (strcmp("BridgeCreated", discriminator) == 0) {
		return ari_validate_bridge_created(json);
	} else
	if (strcmp("BridgeDestroyed", discriminator) == 0) {
		return ari_validate_bridge_destroyed(json);
	} else
	if (strcmp("BridgeMerged", discriminator) == 0) {
		return ari_validate_bridge_merged(json);
	} else
	if (strcmp("ChannelCallerId", discriminator) == 0) {
		return ari_validate_channel_caller_id(json);
	} else
	if (strcmp("ChannelCreated", discriminator) == 0) {
		return ari_validate_channel_created(json);
	} else
	if (strcmp("ChannelDestroyed", discriminator) == 0) {
		return ari_validate_channel_destroyed(json);
	} else
	if (strcmp("ChannelDialplan", discriminator) == 0) {
		return ari_validate_channel_dialplan(json);
	} else
	if (strcmp("ChannelDtmfReceived", discriminator) == 0) {
		return ari_validate_channel_dtmf_received(json);
	} else
	if (strcmp("ChannelEnteredBridge", discriminator) == 0) {
		return ari_validate_channel_entered_bridge(json);
	} else
	if (strcmp("ChannelHangupRequest", discriminator) == 0) {
		return ari_validate_channel_hangup_request(json);
	} else
	if (strcmp("ChannelLeftBridge", discriminator) == 0) {
		return ari_validate_channel_left_bridge(json);
	} else
	if (strcmp("ChannelStateChange", discriminator) == 0) {
		return ari_validate_channel_state_change(json);
	} else
	if (strcmp("ChannelUserevent", discriminator) == 0) {
		return ari_validate_channel_userevent(json);
	} else
	if (strcmp("ChannelVarset", discriminator) == 0) {
		return ari_validate_channel_varset(json);
	} else
	if (strcmp("PlaybackFinished", discriminator) == 0) {
		return ari_validate_playback_finished(json);
	} else
	if (strcmp("PlaybackStarted", discriminator) == 0) {
		return ari_validate_playback_started(json);
	} else
	if (strcmp("StasisEnd", discriminator) == 0) {
		return ari_validate_stasis_end(json);
	} else
	if (strcmp("StasisStart", discriminator) == 0) {
		return ari_validate_stasis_start(json);
	} else
	{
		ast_log(LOG_ERROR, "ARI Event has undocumented subtype %s\n",
			discriminator);
		res = 0;
	}

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Event field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Event field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI Event field type failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI Event has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI Event missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI Event missing required field type\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_event_fn(void)
{
	return ari_validate_event;
}

int ari_validate_playback_finished(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_playback = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI PlaybackFinished field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI PlaybackFinished field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI PlaybackFinished field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("playback", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_playback = 1;
			prop_is_valid = ari_validate_playback(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI PlaybackFinished field playback failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI PlaybackFinished has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI PlaybackFinished missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI PlaybackFinished missing required field type\n");
		res = 0;
	}

	if (!has_playback) {
		ast_log(LOG_ERROR, "ARI PlaybackFinished missing required field playback\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_playback_finished_fn(void)
{
	return ari_validate_playback_finished;
}

int ari_validate_playback_started(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_playback = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI PlaybackStarted field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI PlaybackStarted field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI PlaybackStarted field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("playback", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_playback = 1;
			prop_is_valid = ari_validate_playback(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI PlaybackStarted field playback failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI PlaybackStarted has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI PlaybackStarted missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI PlaybackStarted missing required field type\n");
		res = 0;
	}

	if (!has_playback) {
		ast_log(LOG_ERROR, "ARI PlaybackStarted missing required field playback\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_playback_started_fn(void)
{
	return ari_validate_playback_started;
}

int ari_validate_stasis_end(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_channel = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StasisEnd field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StasisEnd field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StasisEnd field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StasisEnd field channel failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI StasisEnd has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI StasisEnd missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI StasisEnd missing required field type\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI StasisEnd missing required field channel\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_stasis_end_fn(void)
{
	return ari_validate_stasis_end;
}

int ari_validate_stasis_start(struct ast_json *json)
{
	int res = 1;
	struct ast_json_iter *iter;
	int has_application = 0;
	int has_type = 0;
	int has_args = 0;
	int has_channel = 0;

	for (iter = ast_json_object_iter(json); iter; iter = ast_json_object_iter_next(json, iter)) {
		if (strcmp("application", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_application = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StasisStart field application failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("timestamp", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			prop_is_valid = ari_validate_date(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StasisStart field timestamp failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("type", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_type = 1;
			prop_is_valid = ari_validate_string(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StasisStart field type failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("args", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_args = 1;
			prop_is_valid = ari_validate_list(
				ast_json_object_iter_value(iter),
				ari_validate_string);
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StasisStart field args failed validation\n");
				res = 0;
			}
		} else
		if (strcmp("channel", ast_json_object_iter_key(iter)) == 0) {
			int prop_is_valid;
			has_channel = 1;
			prop_is_valid = ari_validate_channel(
				ast_json_object_iter_value(iter));
			if (!prop_is_valid) {
				ast_log(LOG_ERROR, "ARI StasisStart field channel failed validation\n");
				res = 0;
			}
		} else
		{
			ast_log(LOG_ERROR,
				"ARI StasisStart has undocumented field %s\n",
				ast_json_object_iter_key(iter));
			res = 0;
		}
	}

	if (!has_application) {
		ast_log(LOG_ERROR, "ARI StasisStart missing required field application\n");
		res = 0;
	}

	if (!has_type) {
		ast_log(LOG_ERROR, "ARI StasisStart missing required field type\n");
		res = 0;
	}

	if (!has_args) {
		ast_log(LOG_ERROR, "ARI StasisStart missing required field args\n");
		res = 0;
	}

	if (!has_channel) {
		ast_log(LOG_ERROR, "ARI StasisStart missing required field channel\n");
		res = 0;
	}

	return res;
}

ari_validator ari_validate_stasis_start_fn(void)
{
	return ari_validate_stasis_start;
}
