#!/bin/bash
#
# chkconfig: 2345 99 15
# description: Open source PBX 
# processname: asterisk

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0

case "$1" in
  start)
	echo -n "Starting Asterisk PBX: "
	/sbin/modprobe ixj	
	daemon /usr/sbin/asterisk
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/asterisk
	;;
  stop)
	echo -n "Shutting Asterisk PBX: "
	killproc asterisk
	/sbin/rmmod -r ixj	
	RETVAL=$?

	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/asterisk
	;;
  restart|reload)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  status)
	status asterisk
	RETVAL=$?
	;;
  *)
	echo "Usage: asterisk {start|stop|status|restart|reload}"
	exit 1
esac

exit $RETVAL

